version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - saturnism
  assignees:
  - saturnism
  ignore:
  - dependency-name: com.vaadin:vaadin-maven-plugin
    versions:
    - 15.0.5
    - 19.0.5
  - dependency-name: com.vaadin:vaadin-bom
    versions:
    - 15.0.5
    - 19.0.5
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.github.lognet:grpc-spring-boot-starter
    versions:
    - 4.4.3
    - 4.4.4
    - 4.4.5
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
